"""Finite-support population checks for the configured two-class DGP.

All calculations sum the population law, with floating-point tolerances. They
do not simulate data, test finite-sample estimator performance, or establish
asymptotic guarantees. X is fixed and is not generated by this simulator.
The approved measurement restriction marginalizes Z; it does not condition on Z.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path

import numpy as np

if __package__:
    from .latent_mnar_sim import (
        _calibrate_intercept,
        _pair_cell_probability,
        binary_product_mixture_joint,
        expit,
        load_config,
    )
else:
    from latent_mnar_sim import (
        _calibrate_intercept,
        _pair_cell_probability,
        binary_product_mixture_joint,
        expit,
        load_config,
    )


DEFAULT_CONFIG = Path(__file__).with_name("config.yml")
TOLERANCE = 1e-10
AXES = ("F", "W", "Y1", "Y2", "Y3", "Z0", "Z1", "D0", "D1")


def _array(value: object, shape: tuple[int, ...], name: str) -> np.ndarray:
    try:
        result = np.asarray(value, dtype=float)
    except (TypeError, ValueError) as error:
        raise ValueError(f"{name} must be a finite numeric array of shape {shape}") from error
    if result.shape != shape or not np.isfinite(result).all():
        raise ValueError(f"{name} must be a finite numeric array of shape {shape}")
    return result


def _probabilities(value: object, shape: tuple[int, ...], name: str) -> np.ndarray:
    result = _array(value, shape, name)
    if not ((result > 0) & (result < 1)).all():
        raise ValueError(f"{name} must lie strictly between 0 and 1")
    return result


def _parameters(config: dict) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, np.ndarray]:
    """Reject configurations outside the actual simulator's fixed dimensions."""
    try:
        model = config["model"]
        if model["latent_classes"] != 2:
            raise ValueError("model.latent_classes must equal 2")
        if model["observed_features"] != ["W", "Y1", "Y2", "Y3"]:
            raise ValueError("model.observed_features must equal [W, Y1, Y2, Y3]")
        if model["state_cardinality"] != [2, 2, 2, 2]:
            raise ValueError("model.state_cardinality must equal [2, 2, 2, 2]")
        weights = _probabilities(model["class_probability"], (2,), "class_probability")
        if not np.isclose(weights.sum(), 1.0, atol=TOLERANCE, rtol=0):
            raise ValueError("class_probability must sum to 1")
        measurement = _probabilities(
            [model["bernoulli_probability"][name] for name in ("W", "Y1", "Y2", "Y3")],
            (4, 2),
            "bernoulli_probability",
        )
        pairs = config["supported_pairs"]
        if pairs not in ([[0, 1], [0, 2]], [[0, 2], [0, 1]]):
            raise ValueError("supported_pairs must contain [0, 1] and [0, 2] exactly once")
        if config["shadow"]["categories"] != 4:
            raise ValueError("shadow.categories must equal 4")
        shadow = _probabilities(
            config["shadow"]["probability_given_pair_cell"], (4, 4),
            "shadow.probability_given_pair_cell",
        )
        if not np.allclose(shadow.sum(axis=1), 1.0, atol=TOLERANCE, rtol=0):
            raise ValueError("shadow.probability_given_pair_cell rows must sum to 1")
        missingness = config["missingness"]
        if missingness["always_observed_anchor"] != "Y1":
            raise ValueError("missingness.always_observed_anchor must equal Y1")
        target = float(_array(
            missingness["target_average_item_observation_rate"], (),
            "target_average_item_observation_rate",
        ))
        if not 1.0 / 3.0 < target < 1.0:
            raise ValueError("target_average_item_observation_rate must lie between 1/3 and 1")
        coefficient = _array(
            [missingness["selection_coefficients"][name] for name in ("Y1", "Yj", "Y1_by_Yj")],
            (3,), "selection_coefficients",
        )
    except (KeyError, TypeError) as error:
        raise ValueError(f"missing or malformed DGP configuration: {error}") from error
    return weights, measurement, shadow, target, coefficient


@dataclass(frozen=True)
class Population:
    """Axes are AXES; D0 and D1 follow supported_pairs, and D_Y1 is always 1."""

    joint: np.ndarray
    pairs: tuple[tuple[int, int], ...]
    propensities: np.ndarray
    intercepts: np.ndarray


def enumerate_population(config: dict, *, shadow_given_class: object = None) -> Population:
    """Enumerate all 2048 cells; an optional class-only Z is a counterexample.

    The default uses the simulator's H[pair_cell, z]. Supplying a strictly
    positive 2-by-4 shadow_given_class replaces it by P(Z_b=z|F=f), independently
    for both blocks. That alternative is only for rank-obstruction diagnostics.
    """
    weights, measurement, shadow, target, coefficient = _parameters(config)
    if shadow_given_class is not None:
        shadow_given_class = _probabilities(shadow_given_class, (2, 4), "shadow_given_class")
        if not np.allclose(shadow_given_class.sum(axis=1), 1, atol=TOLERANCE, rtol=0):
            raise ValueError("shadow_given_class rows must sum to 1")
    pairs = tuple(tuple(pair) for pair in config["supported_pairs"])
    pair_cells = np.asarray([[0, 0], [0, 1], [1, 0], [1, 1]])
    linear = np.column_stack((pair_cells, pair_cells.prod(axis=1))) @ coefficient
    intercepts = np.asarray([
        _calibrate_intercept(linear, (3 * target - 1) / 2, _pair_cell_probability(config, pair[1]))
        for pair in pairs
    ])
    propensities = expit(intercepts[:, None] + linear[None, :])
    component_law = np.stack([
        binary_product_mixture_joint(np.eye(2)[f], measurement)[1].reshape(2, 2, 2, 2)
        for f in range(2)
    ])
    coordinates = np.indices((2, 2, 2, 2, 2, 4, 4, 2, 2))
    f = coordinates[0]
    joint = weights[f] * component_law[tuple(coordinates[:5])]
    for block, pair in enumerate(pairs):
        cell = 2 * coordinates[2 + pair[0]] + coordinates[2 + pair[1]]
        z, d = coordinates[5 + block], coordinates[7 + block]
        kernel = shadow[cell, z] if shadow_given_class is None else shadow_given_class[f, z]
        response = propensities[block, cell]
        joint *= kernel * np.where(d == 1, response, 1 - response)
    return Population(joint, pairs, propensities, intercepts)


def _marginal(joint: np.ndarray, axes: tuple[int, ...]) -> np.ndarray:
    remaining = tuple(sorted(axes))
    result = joint.sum(axis=tuple(axis for axis in range(joint.ndim) if axis not in axes))
    return result.transpose(tuple(remaining.index(axis) for axis in axes))


def _error(left: np.ndarray, right: np.ndarray) -> float:
    return float(np.max(np.abs(left - right)))


def _rank(matrix: np.ndarray) -> dict:
    singular = np.linalg.svd(matrix, compute_uv=False)
    return {
        "rank": int(np.count_nonzero(singular > TOLERANCE)),
        "shape": list(matrix.shape),
        "singular_values": singular.tolist(),
    }


def _block_checks(population: Population, block: int) -> dict:
    pair = population.pairs[block]
    # P(W, pair_cell, Z_b, D_b), after summing F and every other variable.
    table = _marginal(population.joint, (1, 2 + pair[0], 2 + pair[1], 5 + block, 7 + block))
    table = table.reshape(2, 4, 4, 2)
    complete = table[..., 1]
    full = table.sum(axis=-1)
    conditional_response = complete / full
    pair_response = complete.sum(axis=2) / full.sum(axis=2)
    exclusion_error = _error(conditional_response, pair_response[:, :, None])
    propensity_error = _error(conditional_response, population.propensities[block][None, :, None])
    operators = []
    recovery_error = 0.0
    for w in range(2):
        # Rows index Z, columns pair cells. A is the simulator's bridge design.
        design = complete[w].T / full[w].sum(axis=0)[:, None]
        conditional = complete[w].T / complete[w].sum(axis=0)[:, None]
        bridge_error = _error(design @ (1 / population.propensities[block]), np.ones(4))
        recovered_pair = (complete[w] / population.propensities[block, :, None]).sum(axis=1)
        recovery_error = max(recovery_error, _error(recovered_pair, full[w].sum(axis=1)))
        operators.append({
            "w": w,
            "bridge_design": {**_rank(design), "matrix": design.tolist()},
            "complete_case": {**_rank(conditional), "matrix": conditional.tolist()},
            "inverse_bridge_moment_error": bridge_error,
        })
    return {
        "pair": [f"Y{item + 1}" for item in pair],
        "response_rate": float(complete.sum()),
        "response_rates_given_w": (complete.sum(axis=(1, 2)) / full.sum(axis=(1, 2))).tolist(),
        "selection_exclusion_error": exclusion_error,
        "selection_equation_error": propensity_error,
        "minimum_pair_w_mass": float(full.sum(axis=2).min()),
        "minimum_instrument_w_mass": float(full.sum(axis=1).min()),
        "pair_law_recovery_error": recovery_error,
        "operators": operators,
    }


def _strong_exclusion(population: Population) -> dict:
    law = _marginal(population.joint, (0, 1, 2, 3, 4, 5, 6))
    conditional = law / law.sum(axis=(2, 3, 4), keepdims=True)
    marginal = law.sum(axis=(5, 6))
    marginal /= marginal.sum(axis=(2, 3, 4), keepdims=True)
    difference = _error(conditional, marginal[..., None, None])
    return {
        "restriction": "Y independent of (Z0,Z1) given (F,W); X fixed",
        "holds": difference <= TOLERANCE,
        "max_absolute_difference": difference,
        "required_for_weak_model": False,
    }


def _recover_anchor(tensor: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Two-class algebraic recovery, ordered once by P(Y1=1|F)."""
    # T(W=1) T(W summed)^-1 = M1 diag(P(W=1|F)) M1^-1.
    pencil = np.linalg.solve(tensor.sum(axis=2).T, tensor[:, :, 1].T).T
    _, anchor = np.linalg.eig(pencil)
    anchor = np.real_if_close(anchor)
    if np.iscomplexobj(anchor):
        raise ValueError("anchor spectral recovery produced complex components")
    anchor /= anchor.sum(axis=0, keepdims=True)
    anchor = anchor[:, np.argsort(anchor[1])]
    latent_by_item_w = np.linalg.solve(anchor, tensor.reshape(2, 4)).reshape(2, 2, 2)
    weights = latent_by_item_w.sum(axis=(1, 2))
    second = latent_by_item_w.sum(axis=2).T / weights
    shifter = latent_by_item_w.sum(axis=1).T / weights
    return anchor, second, shifter, weights


def _latent_checks(population: Population, weights: np.ndarray, measurement: np.ndarray) -> dict:
    kernels = np.stack((1 - measurement, measurement), axis=1)
    ranks = {name: _rank(kernel) for name, kernel in zip(("W", "Y1", "Y2", "Y3"), kernels)}
    # For two positive nonzero columns, column Kruskal rank equals matrix rank.
    kruskal_sum = sum(ranks[name]["rank"] for name in ("Y1", "Y2", "W"))
    shared = np.einsum("af,wf->awf", kernels[1], kernels[0]).reshape(4, 2)
    inversion = weights[:, None] * shared.T
    result = {
        "kernel_ranks": ranks,
        "anchor_kruskal_sum": kruskal_sum,
        "required_anchor_kruskal_sum": 6,
        "shared_khatri_rao": _rank(shared),
        "weighted_inversion": _rank(inversion),
        "anchor_order_gap": float(abs(measurement[1, 1] - measurement[1, 0])),
        "extension_kruskal_sum": sum(ranks[name]["rank"] for name in ("Y1", "Y3", "W")),
        "extension_condition": "Only shared inversion rank 2 is required; a new Kruskal bound is not required.",
    }
    if kruskal_sum < 6 or result["weighted_inversion"]["rank"] < 2:
        result["recovery"] = {"passed": False, "reason": "anchor or shared inversion rank is deficient"}
        return result
    anchor_tensor = _marginal(population.joint, (2, 3, 1))
    anchor, second, shifter, recovered_weights = _recover_anchor(anchor_tensor)
    recovered_shared = np.einsum("af,wf->awf", anchor, shifter).reshape(4, 2)
    recovered_inversion = recovered_weights[:, None] * recovered_shared.T
    extension_tensor = _marginal(population.joint, (4, 2, 1))
    third = extension_tensor.reshape(2, 4) @ np.linalg.pinv(recovered_inversion)
    order = np.argsort(measurement[1])
    recovered_kernels = np.stack((shifter, anchor, second, third))
    kernel_error = _error(recovered_kernels, kernels[:, :, order])
    weight_error = _error(recovered_weights, weights[order])
    tensor_error = _error(third @ recovered_inversion, extension_tensor.reshape(2, 4))
    true_posterior = weights[None, :] * kernels[0]
    true_posterior /= true_posterior.sum(axis=1, keepdims=True)
    posterior = recovered_weights[None, :] * shifter
    posterior /= posterior.sum(axis=1, keepdims=True)
    posterior_error = _error(posterior, true_posterior[:, order])
    result["recovery"] = {
        "passed": max(kernel_error, weight_error, tensor_error, posterior_error) <= TOLERANCE,
        "label_rule": "Increasing P(Y1=1|F); identical labels used in every W stratum and the Y3 inversion",
        "configured_class_order": order.tolist(),
        "class_probability": recovered_weights.tolist(),
        "bernoulli_probability": dict(zip(("W", "Y1", "Y2", "Y3"), recovered_kernels[:, 1, :].tolist())),
        "class_probability_given_w": posterior.tolist(),
        "kernel_error": kernel_error,
        "class_probability_error": weight_error,
        "extension_tensor_error": tensor_error,
        "class_posterior_error": posterior_error,
    }
    return result


def validate_dgp(config: dict) -> dict:
    """Return JSON-safe checks of the actual configuration and population law."""
    report = {
        "passed": False,
        "scope": (
            "Finite-support population summation with floating-point tolerance; "
            "no Monte Carlo, finite-sample performance claim, or asymptotic guarantee."
        ),
        "measurement_assumption": "P(Y|F,W,X)=product_j Q_j(Y_j|F,X), marginalizing Z; X fixed",
        "absolute_tolerance": TOLERANCE,
        "checks": {},
        "diagnostics": {},
    }
    checks = report["checks"]
    try:
        weights, measurement, shadow, target, _ = _parameters(config)
    except (ValueError, OverflowError) as error:
        checks["configuration"] = {"passed": False, "error": str(error)}
        report["failed_checks"] = ["configuration"]
        return report
    checks["configuration"] = {"passed": True}
    try:
        with np.errstate(divide="raise", invalid="raise", over="raise"):
            population = enumerate_population(config)
            joint = population.joint
            normalization_error = abs(float(joint.sum()) - 1)
            checks["positive_population_support"] = {
                "passed": bool(np.isfinite(joint).all() and joint.min() > 0 and normalization_error <= TOLERANCE),
                "axes": list(AXES), "shape": list(joint.shape), "cells": int(joint.size),
                "minimum_mass": float(joint.min()), "normalization_error": normalization_error,
            }
            minimum, maximum = float(population.propensities.min()), float(population.propensities.max())
            checks["positive_pair_propensities"] = {
                "passed": 0 < minimum <= maximum < 1,
                "minimum": minimum, "maximum": maximum,
                "intercepts": population.intercepts.tolist(), "by_pair_cell": population.propensities.tolist(),
            }
            marginal = _marginal(joint, (0, 1, 2, 3, 4))
            conditional_y = marginal / marginal.sum(axis=(2, 3, 4), keepdims=True)
            cells = np.indices((2, 2, 2)).reshape(3, -1).T
            product_y = np.where(cells[:, :, None], measurement[None, 1:, :], 1 - measurement[None, 1:, :]).prod(axis=1)
            product_y = product_y.T.reshape(2, 1, 2, 2, 2)
            product_error = _error(conditional_y, product_y)
            y_given_f = marginal.sum(axis=1)
            y_given_f /= y_given_f.sum(axis=(1, 2, 3), keepdims=True)
            exclusion_error = _error(conditional_y, y_given_f[:, None])
            checks["marginal_product_measurement"] = {
                "passed": product_error <= TOLERANCE, "maximum_error": product_error,
            }
            checks["w_measurement_exclusion"] = {
                "passed": exclusion_error <= TOLERANCE, "maximum_error": exclusion_error,
            }
            shadow_rank = _rank(shadow)
            checks["shadow_kernel_rank"] = {"passed": shadow_rank["rank"] == 4, **shadow_rank}
            blocks = [_block_checks(population, block) for block in range(2)]
            report["pairs"] = blocks
            rates = [1.0, 0.0, 0.0]
            for pair, block in zip(population.pairs, blocks):
                rates[pair[1]] = block["response_rate"]
            calibration_error = max(abs(rate - (3 * target - 1) / 2) for rate in rates[1:])
            mean_rate = float(np.mean(rates))
            checks["response_calibration"] = {
                "passed": calibration_error <= TOLERANCE and abs(mean_rate - target) <= TOLERANCE,
                "item_rates": rates, "mean_all_items": mean_rate,
                "target_nonanchor": (3 * target - 1) / 2, "target_mean_all_items": target,
                "maximum_nonanchor_error": calibration_error,
            }
            checks["pair_shadow_selection_exclusion_given_w"] = {
                "passed": all(
                    max(block["selection_exclusion_error"], block["selection_equation_error"]) <= TOLERANCE
                    for block in blocks
                ),
                "restriction": "R_S independent of Z_S given (Y_S,W); X fixed",
            }
            checks["complete_case_rank_each_w"] = {
                "passed": all(
                    operator[name]["rank"] == 4
                    for block in blocks for operator in block["operators"]
                    for name in ("bridge_design", "complete_case")
                ),
                "required_rank": 4,
            }
            checks["population_inverse_bridge"] = {
                "passed": all(
                    block["pair_law_recovery_error"] <= TOLERANCE
                    and all(
                        operator["inverse_bridge_moment_error"] <= TOLERANCE
                        for operator in block["operators"]
                    )
                    for block in blocks
                ),
            }
            latent = _latent_checks(population, weights, measurement)
            report["latent"] = latent
            checks["anchor_kruskal"] = {"passed": latent["anchor_kruskal_sum"] >= 6}
            checks["extension_inversion_rank"] = {
                "passed": latent["shared_khatri_rao"]["rank"] == 2 and latent["weighted_inversion"]["rank"] == 2,
            }
            checks["shared_label_recovery"] = {
                "passed": latent["recovery"]["passed"] and latent["anchor_order_gap"] > TOLERANCE,
            }
            report["diagnostics"]["old_strong_y_z_exclusion"] = {
                **_strong_exclusion(population), "expected_for_repository_default": "violated",
            }
    except (ValueError, ArithmeticError, np.linalg.LinAlgError) as error:
        checks["population_evaluation"] = {"passed": False, "error": str(error)}
    report["failed_checks"] = [name for name, check in checks.items() if not check["passed"]]
    report["passed"] = not report["failed_checks"]
    return report


def class_only_shadow_diagnostic(config: dict, shadow_given_class: object = None) -> dict:
    """Demonstrate the rank-at-most-two obstruction under class-only shadows."""
    if shadow_given_class is None:
        shadow_given_class = [[0.70, 0.15, 0.10, 0.05], [0.05, 0.10, 0.15, 0.70]]
    population = enumerate_population(config, shadow_given_class=shadow_given_class)
    blocks = [_block_checks(population, block) for block in range(2)]
    ranks = [operator["complete_case"]["rank"] for block in blocks for operator in block["operators"]]
    return {
        "mechanism": "P(Z_b|F), independent draws across blocks; counterexample, not the configured simulator",
        "maximum_complete_case_rank": max(ranks),
        "rank_at_most_two": max(ranks) <= 2,
        "passes_rank_four": all(rank == 4 for rank in ranks),
        "old_strong_y_z_exclusion": _strong_exclusion(population),
        "pairs": blocks,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config", type=Path, default=DEFAULT_CONFIG,
        help="JSON-format simulator configuration (default: adjacent config.yml)",
    )
    arguments = parser.parse_args(argv)
    try:
        report = validate_dgp(load_config(arguments.config))
    except (OSError, ValueError) as error:
        report = {
            "passed": False, "failed_checks": ["configuration"],
            "checks": {"configuration": {"passed": False, "error": str(error)}},
        }
    report["config"] = str(arguments.config.resolve())
    print(json.dumps(report, indent=2, allow_nan=False))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
